name: dispatcherz
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  http: ^1.6.0
  cupertino_icons: ^1.0.8
  file_picker: ^10.3.10
  # ※ここに書かれていた flutter_gen の行は削除しました

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true